### ISSUE TITLE
How can I update openh264 to the latest version?

### ISSUE THREAD

**Issue by rachelxj** [DoubangoTelecom/doubango#483]
Hi, 
I'd like to update openh264 to the latest version, would you please me how can I build all those .a (such as libopenh264.a, libdecoder.a, libencoder.a, etc.) files for openh264? I can only get libopenh264.a when I build openh264 for android.

**Comment by luciaark** [comment]
Hi
Do you find the way to update openh264 to the latest version？what i compile in android  cannot be found by my application. Will you let me know your ways?

**Comment by rachelxj** [comment]
I don't use openh264 in the end, I just used ffmpeg

**Comment by cnscns** [comment]
@rachelxj which version ffmpeg do you use?If using new version ffmpeg,  Did you modify the doubango version?
