### ISSUE TITLE
Doubango build using linux host machine

### ISSUE THREAD

**Issue by Ahmedeldeeb91** [DoubangoTelecom/doubango#499]
While building Doubango using a linux based machine (OS = Ubuntu) and choosing the buildall.sh at folder bindings/java/anroid/buildall there is a missing libraries which are not found in the source code which release this errors in compilation and making of tinyWRAP.so
error: cannot find -lwebrtc_aec
error: cannot find -lwebrtc_spl
error: cannot find -lwebrtc_apm_utility
error: cannot find -lwebrtc_nsx
error: cannot find -lwebrtc_system_wrappers
And these libraries doesnot exist in the source code so how will the building will keep progress
i decided to ignore this feature which is called webrtc and try to generate a tinyWRAP.so file but after generating this file and including this file in the lib folder of android-ngn of imsdroid application and tried to install the application on the mobile ..after installation this error occurs whenever i tried to launch imsdroid 
failed: "dlopen failed: missing PT_DYNAMIC in "libtinyWRAP_armv7-a.so"
so i need a documentation for building doubango under linux coz it seems that the included documentation files (such as programmer guide.pdf) are for an older version of doubango .Thanks for advance

**Comment by DoubangoTelecom** [comment]
To build doubango for Android: https://github.com/DoubangoTelecom/imsdroid/blob/master/Building_Doubango.md
